version: '3'
services:
  discord-bot:
    # name of image should the name you provided while building the image
    image: user_name/image_name
    environment:
      # Paste your token_id here
      - TOKEN=token_here
    restart: always